# Name of the GitHub Actions workflow
name: Node.js CI

# Define when the workflow should run
on:
  push: # Run this workflow when changes are pushed
    branches: [main] # Only run on the 'main' branch
  pull_request: # Run this workflow when a pull request is opened
    branches: [main] # Only for pull requests targeting 'main'

# Define the jobs that will run in the workflow
jobs:
  build: # Job name (can be anything)
    runs-on: ubuntu-latest # The virtual machine (OS) the job will run on

    # Run the workflow on multiple Node.js versions
    strategy:
      matrix:
        node-version: [14, 16, 18] # Test on Node.js versions 14, 16, and 18

    # Steps to execute in the workflow
    steps:
      - name: Checkout repository # Step 1: Get the project code from GitHub
        uses: actions/checkout@v3 # This action checks out the repository

      - name: Setup Node.js ${{ matrix.node-version }} # Step 2: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # Use the version from the matrix

      - name: Install dependencies # Step 3: Install project dependencies
        run: npm install # Runs `npm install` to install all dependencies

      - name: Run tests # Step 4: Run the test suite
        run: npm test # Executes Jest tests using the command in package.json
